frontend:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

backend:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

postgres:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi