frontend:
  replicaCount: 3
  resources:
    requests:
      cpu: 500m
      memory: 512Mi

backend:
  replicaCount: 3
  resources:
    requests:
      cpu: 500m
      memory: 512Mi

postgres:
  replicaCount: 1
  resources:
    requests:
      cpu: 500m
      memory: 512Mi