apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app
          image: ttl.sh/wito-hello-app:1h
          imagePullPolicy: Always
          ports:
            - name: http-web
              containerPort: 8080
